from app.api.v1.monitoring.models import AlertType


ALERT_RULE_SOURCE_TARGET = "target"
ALERT_RULE_SOURCE_GLOBAL = "global"
ALERT_RULE_SOURCE_DEFAULT = "default"

ALERT_RULE_SOURCES = (
    ALERT_RULE_SOURCE_TARGET,
    ALERT_RULE_SOURCE_GLOBAL,
    ALERT_RULE_SOURCE_DEFAULT,
)

MAX_ALERT_RULE_COOLDOWN_MINUTES = 10_080

SUPPORTED_TARGET_ALERT_TYPES = (
    AlertType.PRICE_DROPPED,
    AlertType.PRICE_INCREASED,
    AlertType.BECAME_AVAILABLE,
    AlertType.BECAME_UNAVAILABLE,
    AlertType.RATING_CHANGED,
    AlertType.REVIEWS_COUNT_CHANGED,
    AlertType.TITLE_CHANGED,
)

NUMERIC_ALERT_TYPES = (
    AlertType.PRICE_DROPPED,
    AlertType.PRICE_INCREASED,
    AlertType.RATING_CHANGED,
    AlertType.REVIEWS_COUNT_CHANGED,
)
