# Generated by Django 6.0.2 on 2026-06-05 13:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marketplace', models.CharField(choices=[('wb', 'Wildberries'), ('ozon', 'Ozon')], max_length=20)),
                ('role', models.CharField(choices=[('own', 'Own product'), ('competitor', 'Competitor product')], default='competitor', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed')], default='active', max_length=20)),
                ('url', models.URLField(max_length=2000)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('check_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('price_changed', 'Price changed'), ('price_dropped', 'Price dropped'), ('price_increased', 'Price increased'), ('availability_changed', 'Availability changed'), ('became_available', 'Became available'), ('became_unavailable', 'Became unavailable'), ('rating_changed', 'Rating changed'), ('reviews_count_changed', 'Reviews count changed'), ('title_changed', 'Title changed')], max_length=50)),
                ('threshold_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum percent change required to trigger this rule.', max_digits=7, null=True)),
                ('threshold_absolute', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum absolute value change required to trigger this rule.', max_digits=12, null=True)),
                ('cooldown_minutes', models.PositiveIntegerField(default=360, help_text='Do not send the same alert too often.')),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='monitoring.monitoringtarget')),
            ],
            options={
                'ordering': ['alert_type'],
            },
        ),
        migrations.CreateModel(
            name='ProductSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parse_status', models.CharField(choices=[('success', 'Success'), ('not_found', 'Not found'), ('blocked', 'Blocked'), ('parse_error', 'Parse error'), ('marketplace_error', 'Marketplace error')], db_index=True, default='success', max_length=30)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='RUB', max_length=10)),
                ('is_available', models.BooleanField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('reviews_count', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='monitoring.monitoringtarget')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('price_changed', 'Price changed'), ('price_dropped', 'Price dropped'), ('price_increased', 'Price increased'), ('availability_changed', 'Availability changed'), ('became_available', 'Became available'), ('became_unavailable', 'Became unavailable'), ('rating_changed', 'Rating changed'), ('reviews_count_changed', 'Reviews count changed'), ('title_changed', 'Title changed')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='new', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('dedup_key', models.CharField(db_index=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.monitoringtarget')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.productsnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitoringtarget',
            index=models.Index(fields=['user', 'marketplace'], name='monitoring__user_id_625021_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringtarget',
            index=models.Index(fields=['marketplace', 'external_id'], name='monitoring__marketp_b98d87_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringtarget',
            index=models.Index(fields=['is_active', 'next_check_at'], name='monitoring__is_acti_dd9fca_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringtarget',
            index=models.Index(fields=['status', 'next_check_at'], name='monitoring__status_412e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['user', 'alert_type'], name='monitoring__user_id_21cc09_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['target', 'alert_type'], name='monitoring__target__dcadd2_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['is_enabled'], name='monitoring__is_enab_02f067_idx'),
        ),
        migrations.AddIndex(
            model_name='productsnapshot',
            index=models.Index(fields=['target', '-checked_at'], name='monitoring__target__0a831f_idx'),
        ),
        migrations.AddIndex(
            model_name='productsnapshot',
            index=models.Index(fields=['parse_status', 'checked_at'], name='monitoring__parse_s_bfcc89_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', '-created_at'], name='monitoring__user_id_84ecfa_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['target', '-created_at'], name='monitoring__target__08b27d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', '-created_at'], name='monitoring__alert_t_fbd5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='monitoring__status_4b15ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('dedup_key',), name='unique_monitoring_alert_dedup_key'),
        ),
    ]
