# Generated by Django 6.0.2 on 2026-06-16 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCacheEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "marketplace",
                    models.CharField(
                        choices=[("wb", "Wildberries"), ("ozon", "Ozon")], max_length=20
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=255)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("seller_name", models.CharField(blank=True, max_length=255)),
                ("brand", models.CharField(blank=True, max_length=255)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("parsed_at", models.DateTimeField(db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("effective_cache_minutes", models.PositiveIntegerField(default=60)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="productsnapshot",
            name="source",
            field=models.CharField(
                choices=[
                    ("parser", "Parser"),
                    ("cache", "Cache"),
                    ("stale_cache", "Stale cache"),
                ],
                db_index=True,
                default="parser",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="productsnapshot",
            index=models.Index(
                fields=["source", "-checked_at"], name="monitoring__source_22dc4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcacheentry",
            index=models.Index(
                fields=["marketplace", "external_id"],
                name="monitoring__marketp_1092be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productcacheentry",
            index=models.Index(
                fields=["expires_at"], name="monitoring__expires_99957c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcacheentry",
            index=models.Index(
                fields=["parsed_at"], name="monitoring__parsed__eefdf5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productcacheentry",
            constraint=models.UniqueConstraint(
                fields=("marketplace", "external_id"),
                name="unique_monitoring_product_cache_entry",
            ),
        ),
    ]
