# Generated by Django 6.0.2 on 2026-06-17 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0002_productcacheentry_productsnapshot_source_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsnapshot",
            old_name="old_price",
            new_name="old_price_cents",
        ),
        migrations.RenameField(
            model_name="productsnapshot",
            old_name="price",
            new_name="price_cents",
        ),
    ]
