# Generated by Django 6.0.2 on 2026-06-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitoring",
            "0003_rename_old_price_productsnapshot_old_price_cents_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="productsnapshot",
            old_name="old_price_cents",
            new_name="old_price",
        ),
        migrations.RenameField(
            model_name="productsnapshot",
            old_name="price_cents",
            new_name="price",
        ),
    ]
