# Generated by Django 6.0.2 on 2026-06-19 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitoring",
            "0004_rename_old_price_cents_productsnapshot_old_price_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="cooldown_minutes",
            field=models.PositiveIntegerField(
                default=360,
                help_text="Do not create the same alert type for this target too often.",
            ),
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target__isnull", False)),
                fields=("target", "alert_type"),
                name="unique_monitoring_target_alert_rule",
            ),
        ),
        migrations.AddConstraint(
            model_name="alertrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("target__isnull", True)),
                fields=("user", "alert_type"),
                name="unique_monitoring_global_alert_rule",
            ),
        ),
    ]
