# Generated by Django 6.0.2 on 2026-04-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_line_total_cents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencykey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
