# Generated by Django 6.0.2 on 2026-05-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_outboxevent_attempts_outboxevent_available_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
