# Generated by Django 6.0.2 on 2026-03-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('event_id', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'received_at'], name='payments_pr_provide_94b427_idx')],
                'unique_together': {('provider', 'event_id')},
            },
        ),
    ]
