# Generated by Django 6.0.2 on 2026-05-01 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_idempotencykey_created_at'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('mock', 'Mock')], default='mock', max_length=64)),
                ('provider_payment_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='created', max_length=32)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'provider_payment_id'], name='payments_pa_provide_3e1786_idx'), models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'), models.Index(fields=['order', 'created_at'], name='payments_pa_order_i_4d9364_idx')],
            },
        ),
    ]
