# Generated by Django 6.0.2 on 2026-06-08 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('webhook', 'Webhook')], max_length=32, verbose_name='Тип канала')),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Telegram chat ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('webhook_url', models.URLField(blank=True, default='', verbose_name='Webhook URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Канал уведомлений',
                'verbose_name_plural': 'Каналы уведомлений',
                'db_table': 'notification_channels',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32, verbose_name='Статус')),
                ('message_text', models.TextField(blank=True, default='', verbose_name='Текст сообщения')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to='monitoring.alert', verbose_name='Alert')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notifications.notificationchannel', verbose_name='Канал уведомления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доставка уведомления',
                'verbose_name_plural': 'Доставки уведомлений',
                'db_table': 'notification_deliveries',
            },
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['user', 'type'], name='notificatio_user_id_a0488f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['type', 'is_active'], name='notificatio_type_e20b5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationchannel',
            constraint=models.UniqueConstraint(fields=('user', 'type', 'telegram_chat_id'), name='unique_user_telegram_channel'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_495627_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['alert', 'status'], name='notificatio_alert_i_a37c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['created_at'], name='notificatio_created_fee8f7_idx'),
        ),
    ]
