# Generated by Django 6.0.2 on 2026-06-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='enabled_alert_types',
            field=models.JSONField(blank=True, default=list, help_text='Пустой список означает, что канал получает все типы alert.', verbose_name='Включенные типы alert'),
        ),
    ]
